const Meta = () => {
  return (
      <>
          <title>🚀Space-website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </>
  );
};

export default Meta;
